apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre
  template:
    metadata:
      labels:
        app: sre
    spec:
      containers:
        - name: sre-app
          image: sre-candidate:latest
          ports:
            - containerPort: 8080 # FIX: Added hyphen
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080 #Fixed
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080 # Fixed
            initialDelaySeconds: 5
            periodSeconds: 10
